using UnityEngine;

public class ZombieScript : MonoBehaviour
{
    public GameObject bloodFXPrefab;
    private float speed = 1f;

    private Rigidbody mybody;
    private bool isAlive;
    void Start()
    {
        mybody = GetComponent<Rigidbody>();
        speed = Random.Range(1f, 5f);
        isAlive = true;
    }

    void Update()
    {
        mybody.linearVelocity = new Vector3(0, 0, -speed);
        if (transform.position.y < -5f)
        {
            gameObject.SetActive(false);
        }
    }

    void die()
    {
        isAlive = false;
        mybody.linearVelocity = Vector3.zero;
        GetComponent<Collider>().enabled = false;
        GetComponentInChildren<Animator>().Play("Idle");

        transform.rotation = Quaternion.Euler(90f, 0f, 0f);
        transform.localScale = new Vector3(1f, 1f, 0.2f);
        transform.position = new Vector3(transform.position.x, 0.2f, transform.position.z);
    }

    void DeactivateGameObject()
    {
        gameObject.SetActive(false);
    }

    void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.CompareTag("Player"))
        {
            Instantiate(bloodFXPrefab, transform.position, Quaternion.identity);
            Invoke("DeactivateGameObject", 3f);

            GamePlayController.instance.IncreaseScore();
            die();
        }
        else if (collision.gameObject.CompareTag("Bullet"))
        {
            Instantiate(bloodFXPrefab, transform.position, Quaternion.identity);
            Destroy(collision.gameObject);
            die();
        }
    }
}
